#!/usr/bin/env python3
"""
render_index.py

Generate a markdown index from validated attack corpus YAML entries.

Usage:
    python scripts/render_index.py
    python scripts/render_index.py --output docs/INDEX.md
    python scripts/render_index.py --format json --output build/corpus_index.json
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("error: PyYAML required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_ATTACKS_DIR = REPO_ROOT / "attacks"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "INDEX.md"


def load_entries(attacks_dir: Path) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for path in sorted(attacks_dir.glob("*.yaml")) + sorted(attacks_dir.glob("*.yml")):
        with path.open(encoding="utf-8") as handle:
            data = yaml.safe_load(handle)
        if isinstance(data, dict):
            data["_file"] = path.name
            entries.append(data)
    entries.sort(key=lambda item: item.get("id", ""))
    return entries


def render_markdown(entries: list[dict[str, Any]]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    severity_counts = Counter(entry.get("severity", "unknown") for entry in entries)
    tactic_counts = Counter(entry.get("tactic", "unspecified") for entry in entries)

    lines = [
        "# Attack Corpus Index",
        "",
        f"**Author:** Soubhagya  ",
        f"**Generated:** {now} (UTC)  ",
        f"**Total entries:** {len(entries)}",
        "",
        "## Summary",
        "",
        "### By severity",
        "",
        "| Severity | Count |",
        "|----------|-------|",
    ]

    for severity in ["critical", "high", "medium", "low", "informational"]:
        count = severity_counts.get(severity, 0)
        if count:
            lines.append(f"| {severity} | {count} |")

    lines.extend([
        "",
        "### By tactic",
        "",
        "| Tactic | Count |",
        "|--------|-------|",
    ])

    for tactic, count in sorted(tactic_counts.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"| `{tactic}` | {count} |")

    lines.extend([
        "",
        "## Entry catalog",
        "",
        "| ID | Title | Severity | Tactic | Technique | File |",
        "|----|-------|----------|--------|-----------|------|",
    ])

    for entry in entries:
        entry_id = entry.get("id", "")
        title = entry.get("title", "").replace("|", "\\|")
        severity = entry.get("severity", "")
        tactic = entry.get("tactic", "")
        technique = entry.get("technique", "")
        filename = entry.get("_file", "")
        lines.append(
            f"| `{entry_id}` | {title} | {severity} | {tactic} | {technique} | `{filename}` |"
        )

    lines.extend([
        "",
        "## Tag index",
        "",
    ])

    tag_map: dict[str, list[str]] = {}
    for entry in entries:
        for tag in entry.get("tags") or []:
            tag_map.setdefault(tag, []).append(entry.get("id", ""))

    for tag in sorted(tag_map):
        ids = ", ".join(f"`{item}`" for item in sorted(tag_map[tag]))
        lines.append(f"- **{tag}:** {ids}")

    lines.extend([
        "",
        "## Related documentation",
        "",
        "- `TAXONOMY.md` — tactic and technique definitions",
        "- `ATTACK_CHAINS.md` — multi stage adversary workflows",
        "- `DETECTION_PLAYBOOK.md` — operational detection rules",
        "- `METHODOLOGY.md` — forensic investigation procedure",
        "",
        "---",
        "",
        "*Auto generated by `scripts/render_index.py`. Do not edit manually.*",
        "",
    ])

    return "\n".join(lines)


def render_json(entries: list[dict[str, Any]]) -> str:
    payload = {
        "author": "Soubhagya",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_entries": len(entries),
        "entries": [
            {
                "id": entry.get("id"),
                "title": entry.get("title"),
                "severity": entry.get("severity"),
                "tactic": entry.get("tactic"),
                "technique": entry.get("technique"),
                "tags": entry.get("tags", []),
                "related_entries": entry.get("related_entries", []),
                "file": entry.get("_file"),
            }
            for entry in entries
        ],
    }
    return json.dumps(payload, indent=2)


def main() -> int:
    parser = argparse.ArgumentParser(description="Render attack corpus index.")
    parser.add_argument(
        "--attacks-dir",
        type=Path,
        default=DEFAULT_ATTACKS_DIR,
        help="Directory containing attack YAML files",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output file path",
    )
    parser.add_argument(
        "--format",
        choices=["markdown", "json"],
        default="markdown",
        help="Output format",
    )
    args = parser.parse_args()

    if not args.attacks_dir.is_dir():
        print(f"error: attacks directory not found: {args.attacks_dir}", file=sys.stderr)
        return 1

    entries = load_entries(args.attacks_dir)
    if not entries:
        print(f"error: no entries found in {args.attacks_dir}", file=sys.stderr)
        return 1

    content = render_json(entries) if args.format == "json" else render_markdown(entries)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"rendered {len(entries)} entries to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
